from tkinter import *
import sqlite3
from tkinter.messagebox import *
con=sqlite3.Connection('Tax')
cur=con.cursor()
cur.execute('create table if not exists details(year varchar2(20),first varchar2(20),last varchar2(20),aadh varchar2(20),pan varchar2(20),dob varchar2(20),flat varchar2(20),area varchar2(20),city varchar2(20),state varchar2(20),country varchar2(20),pin varchar2(20),mobile number,email varchar2(20),month varchar2(20),income varchar2(20),tax varchar2(20),medical varchar2(20),home varchar2(20),usr varchar2(20))')
def fun():
    toe.destroy()
    root = Tk()
    root.configure(bg='powder blue')
    root.title("Tax Filing")
    root.minsize(1500,1350)
    Label(root,text="Online Income Tax Filing",bg="magenta",fg="white",font='times 100 bold').place(x=5,y=5)
    Label(root,text=("Welcome Sir/Mam"),bg="powder blue",fg="blue",font='times 35').place(x=551,y=170)
    Label(root,text=("To use our Tax E-filing "),bg="powder blue",fg="blue",font='times 30').place(x=551,y=250)
    Label(root,text="Enter your Income details",bg="powder blue",fg="blue",font='times 30').place(x=21,y=300)
    Label(root,text="Income from salary/business",bg="powder blue",fg="blue",font='times 19').place(x=21,y=380)
    e=Entry(root,font='times 18',bd=5)
    e.place(x=751,y=380)
    Label(root,text="Income from agricultural property",bg="powder blue",fg="blue",font='times 19').place(x=21,y=460)
    f=Entry(root,font='times 18',bd=5)
    f.place(x=751,y=460)
    Label(root,text="Any other income",bg="powder blue",fg="blue",font='times 19').place(x=21,y=540)
    g=Entry(root,font='times 18',bd=5)
    g.place(x=751,y=540)
    def new():
        root.destroy()
        def check():
            cur.execute('create table if not exists Tax(name varchar2(20),password varchar2(20))')
            cur.execute('insert into Tax values(?,?)',(y.get(),z.get()))
            con.commit()
        def change(y):
            def app(y):
                def payment():
                        print (y.get())
                        cur.execute('insert into details(first,last,aadh,pan,dob,flat,area,city,state,country,pin,mobile,email,month,income,tax,medical,home,usr)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',(n.get(),o.get(),w.get(),p.get(),b.get(),r.get(),q.get(),s.get(),t.get(),u.get(),v.get(),x.get(),c.get(),h.get(),i.get(),j.get(),k.get(),l.get(),y.get()))
                        cur.execute('select * from details')
                        print (cur.fetchall())
                        con.commit()
                        tic=Toplevel()
                        tic.configure(bg='powder blue')
                        tic.title("Payment Page")    
                        tic.minsize(800,610)
                        ab=PhotoImage(file="sbi2.gif")
                        Label(tic,image=ab).place(relx=0.005,rely=0.01)
                        Label(tic,text=("State Bank of India"),fg="blue",font='times 40',bg="powder blue").place(relx=0.37,rely=0.01)
                        Label(tic,text="Payment ID",fg="purple",font='times 18',bg="powder blue").place(relx=0.30,rely=0.2)
                        zz=Entry(tic,font='times 15',bd=5)
                        zz.place(relx=0.7,rely=0.2)
                        Label(tic,text="Enter Amount",fg="purple",font='times 18',bg="powder blue").place(relx=0.30,rely=0.29)
                        yy=Entry(tic,font='times 15',bd=5)
                        yy.place(relx=0.7,rely=0.28)
                        Label(tic,text="Card Number",fg="purple",font='times 18',bg="powder blue").place(relx=0.30,rely=0.38)
                        xx=Entry(tic,font='times 15',bd=5)
                        xx.place(relx=0.7,rely=0.38)
                        Label(tic,text="Expiry Date",fg="purple",font='times 18',bg="powder blue").place(relx=0.30,rely=0.47)
                        ww=Entry(tic,font='times 15',bd=5)
                        ww.place(relx=0.7,rely=0.47)
                        Label(tic,text="Card Holder Name",fg="purple",font='times 18',bg="powder blue").place(relx=0.30,rely=0.56)
                        vv=Entry(tic,font='times 15',bd=5)
                        vv.place(relx=0.7,rely=0.56)
                        Label(tic,text="Entry PIN",fg="purple",font='times 18',bg="powder blue").place(relx=0.30,rely=0.65)
                        uu=Entry(tic,show='*',font='times 15',bd=5)
                        uu.place(relx=0.7,rely=0.65)
                        def see():
                            showinfo("Performed","you have successfully paid you Tax")
                        Button(tic,text="PAY NOW",font='times 15',bd=5,command=see).place(relx=0.40,rely=0.80)
                        Label(tic,text="Please do not click back/refresh the page/close while the transaction is processing",fg="olive",font='times 16',bg="powder blue").place(relx=0.05,rely=0.9)
                        tic.mainloop()
                def insert(y):
                    def payment():
                        
                        tic=Toplevel()
                        tic.configure(bg='powder blue')
                        tic.title("Payment Page")    
                        tic.minsize(800,610)
                        ab=PhotoImage(file="sbi2.gif")
                        Label(tic,image=ab).place(relx=0.005,rely=0.01)
                        Label(tic,text=("State Bank of India"),fg="blue",font='times 40',bg="powder blue").place(relx=0.37,rely=0.01)
                        Label(tic,text="Payment ID",fg="mediumvioletred",font='times 18',bg="powder blue").place(relx=0.30,rely=0.2)
                        zz=Entry(tic,font='times 15',bd=5)
                        zz.place(relx=0.7,rely=0.2)
                        Label(tic,text="Enter Amount",fg="mediumvioletred",font='times 18',bg="powder blue").place(relx=0.30,rely=0.29)
                        yy=Entry(tic,font='times 15',bd=5)
                        yy.place(relx=0.7,rely=0.28)
                        Label(tic,text="Card Number",fg="mediumvioletred",font='times 18',bg="powder blue").place(relx=0.30,rely=0.38)
                        xx=Entry(tic,font='times 15',bd=5)
                        xx.place(relx=0.7,rely=0.38)
                        Label(tic,text="Expiry Date",fg="mediumvioletred",font='times 18',bg="powder blue").place(relx=0.30,rely=0.47)
                        ww=Entry(tic,font='times 15',bd=5)
                        ww.place(relx=0.7,rely=0.47)
                        Label(tic,text="Card Holder Name",fg="mediumvioletred",font='times 18',bg="powder blue").place(relx=0.30,rely=0.56)
                        vv=Entry(tic,font='times 15',bd=5)
                        vv.place(relx=0.7,rely=0.56)
                        Label(tic,text="Entry PIN",fg="mediumvioletred",font='times 18',bg="powder blue").place(relx=0.30,rely=0.65)
                        uu=Entry(tic,show='*',font='times 15',bd=5)
                        uu.place(relx=0.7,rely=0.65)
                        def see():
                            showinfo("Performed","You have successfully paid your Tax")
                        Button(tic,text="PAY NOW",font='times 15',bd=5,command=see).place(relx=0.40,rely=0.80)
                        Label(tic,text="Please do not click back/refresh the page/close while the transaction is processing",fg="olive",font='times 16',bg="powder blue").place(relx=0.05,rely=0.9)
                        tic.mainloop()
                    su=0
                    cur.execute('select 1 from details where usr=?',(y.get(),))
                    fd=cur.fetchall()
                    for row in fd:
                        su=row[0]
                    if su==1:
                        cur.execute('select * from details where usr=?',(y.get(),))
                        hg=cur.fetchall()
                        ry=Tk()
                        ry=Toplevel()
                        ry.configure(bg='powder blue')
                        ry.title("Tax Filing")
                        ry.minsize(1000,1000)
                        for row in hg:
                            xy=PhotoImage(file="pen2.gif")
                            Label(ry,image=xy).place(x=10,y=20)
                            Label(ry,text='Online Income Tax Filing',bg="powder blue",fg="black",font='times 40').place(x=350,y=20)
                            Label(ry,text='Last Date Of Tax Filing is 31 March,Hurry Up!!!',bg="powder blue",fg="black",font='times 25').place(x=350,y=100)
                            Label(ry,text='First Name',bg="powder blue",fg="tomato",font='times 20').place(x=351,y=170)
                            Label(ry,text=row[1],bg="powder blue",fg="tomato",font='times 20').place(x=651,y=170)
                            Label(ry,text='Last Name',bg="powder blue",fg="tomato",font='times 20').place(x=351,y=220)
                            Label(ry,text=row[2],bg="powder blue",fg="tomato",font='times 20').place(x=651,y=220)
                            Label(ry,text='Adhaar Number',bg="powder blue",fg="tomato",font='times 20').place(x=351,y=270)
                            Label(ry,text=row[3],bg="powder blue",fg="tomato",font='times 20').place(x=651,y=270)
                            Label(ry,text='Pan Number',bg="powder blue",fg="tomato",font='times 20').place(x=351,y=320)
                            Label(ry,text=row[4],bg="powder blue",fg="tomato",font='times 20').place(x=651,y=320)
                            Label(ry,text='DOB',bg="powder blue",fg="tomato",font='times 20').place(x=351,y=370)
                            Label(ry,text=row[5],bg="powder blue",fg="tomato",font='times 20').place(x=651,y=370)
                            Label(ry,text='Flat',bg="powder blue",fg="tomato",font='times 20').place(x=351,y=420)
                            Label(ry,text=row[6],bg="powder blue",fg="tomato",font='times 20').place(x=651,y=420)
                            Label(ry,text='Area',bg="powder blue",fg="tomato",font='times 20').place(x=351,y=470)
                            Label(ry,text=row[7],bg="powder blue",fg="tomato",font='times 20').place(x=651,y=470)
                            Label(ry,text='City',bg="powder blue",fg="tomato",font='times 20').place(x=351,y=520)
                            Label(ry,text=row[8],bg="powder blue",fg="tomato",font='times 20').place(x=651,y=520)
                            Label(ry,text='State',bg="powder blue",fg="tomato",font='times 20').place(x=351,y=570)
                            Label(ry,text=row[9],bg="powder blue",fg="tomato",font='times 20').place(x=651,y=570)
                            Label(ry,text='Country',bg="powder blue",fg="tomato",font='times 20').place(x=351,y=620)
                            Label(ry,text=row[10],bg="powder blue",fg="tomato",font='times 20').place(x=651,y=620)
                            Label(ry,text='Pin',bg="powder blue",fg="tomato",font='times 20').place(x=351,y=670)
                            Label(ry,text=row[11],bg="powder blue",fg="tomato",font='times 20').place(x=651,y=670)
                            Label(ry,text='Mobile',bg="powder blue",fg="tomato",font='times 20').place(x=351,y=720)
                            Label(ry,text=row[12],bg="powder blue",fg="tomato",font='times 20').place(x=651,y=720)
                            Button(ry,text="Proceed",font='times 16',bd=5,command=payment).place(x=800,y=750)
                        ry.mainloop()
                    else:
                        print (y.get())
                        print ('jhd jhdvvdhcvdjcvjdvchgcvsdhg')
                        cur.execute('insert into details(first,last,aadh,pan,dob,flat,area,city,state,country,pin,mobile,email,month,income,tax,medical,home,usr)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',(n.get(),o.get(),w.get(),p.get(),b.get(),r.get(),q.get(),s.get(),t.get(),u.get(),v.get(),x.get(),c.get(),h.get(),i.get(),j.get(),k.get(),l.get(),y.get()))
                        cur.execute('select * from details')
                        print (cur.fetchall())
                        con.commit()
                        tl.destroy()
                        payment()
                tl=Tk()
                tl.configure(bg='cyan3')
                tl.title("Tax Filing")
                tl.minsize(1200,1600)
                Label(tl,text="Form ITR V",fg="black",font='times 16',bg="cyan3").grid(row=0,column=0,sticky=W)
                Label(tl,text="Assessment Year",fg="black",font='times 15',bg="cyan3").grid(row=0,column=0,sticky=E)
                variable = StringVar(tl)
                variable.set("2016-2017")
                aa=OptionMenu(tl,variable,"2016-2017","2015-2016","2014-2015","2013-2014","2012-2013","2011-2012","2010-2011","2009-2010")
                aa.grid(row=0,column=1)
                Label(tl,text="--------------------------------------Personal Details---------------------------------",fg="black",font='times 17',bg="cyan3").grid(row=1,column=0,sticky=W)
                Label(tl,text="First Name",fg="black",font='times 15',bg="cyan3").grid(row=2,column=0,sticky=W)
                n=Entry(tl,font='times 15',bd=4)
                n.grid(row=2,column=1)
                Label(tl,text="Last Name",fg="black",font='times 15',bg="cyan3").grid(row=3,column=0,sticky=W)
                o=Entry(tl,font='times 15',bd=5)
                o.grid(row=3,column=1)
                Label(tl,text="Aadhaar Number",fg="black",font='times 15',bg="cyan3").grid(row=4,column=0,sticky=W)
                w=Entry(tl,font='times 15',bd=5)
                w.grid(row=4,column=1)
                Label(tl,text="PAN Number",fg="black",font='times 15',bg="cyan3").grid(row=5,column=0,sticky=W)
                p=Entry(tl,font='times 15',bd=5)
                p.grid(row=5,column=1)
                Label(tl,text="Gender",fg="black",font='times 15',bg="cyan3").grid(row=6,column=0,sticky=W)
                v1=IntVar()
                r=Radiobutton(tl,text='Male',variable=v1,value=1)
                r.grid(row=7,column=0,stick=W)
                r1=Radiobutton(tl,text='Female',variable=v1,value=2)
                r1.grid(row=7,column=1,stick=W)
                r2=Radiobutton(tl,text='Third',variable=v1,value=3)
                r2.grid(row=7,column=2,stick=E)
                Label(tl,text="Date Of Birth",fg="black",font='times 15',bg="cyan3").grid(row=8,column=0,sticky=W)
                b=Entry(tl,font='times 15',bd=5)
                b.grid(row=8,column=1)
                Label(tl,text="Flat/Door/Building",fg="black",font='times 15',bg="cyan3").grid(row=9,column=0,sticky=W)
                r=Entry(tl,font='times 15',bd=5)
                r.grid(row=9,column=1)
                Label(tl,text="Area/Locality",fg="black",font='times 15',bg="cyan3").grid(row=10,column=0,sticky=W)
                q=Entry(tl,font='times 15',bd=5)
                q.grid(row=10,column=1)
                Label(tl,text="Town/City/District",fg="black",font='times 15',bg="cyan3").grid(row=11,column=0,sticky=W)
                s=Entry(tl,font='times 15',bd=5)
                s.grid(row=11,column=1)
                Label(tl,text="STATE",fg="black",font='times 15',bg="cyan3").grid(row=12,column=0,sticky=W)
                t=Entry(tl,font='times 15',bd=5)
                t.grid(row=12,column=1)
                Label(tl,text="COUNTRY",fg="black",font='times 15',bg="cyan3").grid(row=13,column=0,sticky=W)
                u=Entry(tl,font='times 15',bd=5)
                u.grid(row=13,column=1)
                Label(tl,text="PIN-CODE",fg="black",font='times 15',bg="cyan3").grid(row=14,column=0,sticky=W)
                v=Entry(tl,font='times 15',bd=5)
                v.grid(row=14,column=1)
                Label(tl,text="Mobile Number",fg="black",font='times 15',bg="cyan3").grid(row=15,column=0,sticky=W)
                x=Entry(tl,font='times 15',bd=5)
                x.grid(row=15,column=1)
                Label(tl,text="E-mail Address",fg="black",font='times 15',bg="cyan3").grid(row=16,column=0,sticky=W)
                c=Entry(tl,font='times 15',bd=5)
                c.grid(row=16,column=1)
                Label(tl,text="--------------------------------------Income Details---------------------------------",fg="black",font='times 17',bg="cyan3").grid(row=17,column=0,sticky=W)
                Label(tl,text="Monthly Income",fg="black",font='times 15',bg="cyan3").grid(row=18,column=0,sticky=W)
                h=Entry(tl,font='times 15',bd=5)
                h.grid(row=18,column=1)
                Label(tl,text="Yearly Income",fg="black",font='times 15',bg="cyan3").grid(row=19,column=0,sticky=W)
                i=Entry(tl,font='times 15',bd=5)
                i.grid(row=19,column=1)
                Label(tl,text="Tax Slab",fg="black",font='times 15',bg="cyan3").grid(row=20,column=0,sticky=W)
                j=Entry(tl,font='times 15',bd=5)
                j.grid(row=20,column=1)
                Label(tl,text="Medical Insurance Premium/if applicable",fg="black",font='times 15',bg="cyan3").grid(row=21,column=0,sticky=W)
                k=Entry(tl,font='times 15',bd=5)
                k.grid(row=21,column=1)
                Label(tl,text="Interest Paid on Home Loan/if applicable",fg="black",font='times 15',bg="cyan3").grid(row=22,column=0,sticky=W)
                l=Entry(tl,font='times 15',bd=5)
                l.grid(row=22,column=1)
                Button(tl,text="Existing User",font='times 16',bd=5,command=lambda:insert(y)).grid(row=17,column=4,sticky=E)
                Button(tl,text="Proceed",font='times 16',bd=5,command=payment).grid(row=20,column=4,sticky=E)
                tl.mainloop()
            i=0
            cur.execute("select 1 from Tax where name=? and password=?",(y.get(),z.get()))
            row=cur.fetchall()
            for i in row:
                i=1
            if i==1:
                app(y)
            else:
                Label(new,text="Doesnot found any account and password is incorrect",font='times=30',fg='crimson',bg='cyan3').grid(row=5,column=1)
        new = Tk()
        new.configure(bg='cyan3')
        new.title("Tax Calculation")    
        new.minsize(1100,1100)
        aaaaa=PhotoImage(file="it.gif")
        Label(new,image=aaaaa).place(relx=0.08,rely=0.009)
        Label(new,text=("Welcome Sir/Mam"),fg="olive",font='times 42',bg="cyan3").place(relx=0.28,rely=0.38) 
        Label(new,text="Enter Your Username",fg="olive",font='times 22',bg="cyan3").place(relx=0.30,rely=0.47)
        y=Entry(new,font='times 15',bd=5)
        y.place(relx=0.55,rely=0.47)
        Label(new,text="Enter Your Password",fg="olive",font='times 22',bg="cyan3").place(relx=0.30,rely=0.52)
        z=Entry(new,show='*',font='times 15',bd=5)
        z.place(relx=0.55,rely=0.52)
        Button(new,text="Submit",font='times 15',bd=5,command=check).place(relx=0.25,rely=0.60)
        Button(new,text="LogIn",font='times 15',bd=5,command=lambda:change(y)).place(relx=0.78,rely=0.60)
        new.mainloop()
    def total():
        a=(int(e.get())+int(f.get())+int(g.get()))
        Label(root,text=('Your Total Income is:',a),font='15').place(x=601,y=650)
        if a>250000:
            Label(root,text=",Your tax slab is 0%",font='15').place(x=911,y=650)
        if a>=250000 and a<500000:
            Label(root,text=",Your tax slab is 5%",font='15').place(x=911,y=650)
        if a>=500000 and a<1000000:
            Label(root,text=",Your tax slab is 10%",font='15').place(x=911,y=650)
        if a>=1000000:
            Label(root,text=",Your tax slab is 30%",font='15').place(x=911,y=650)
    Button(root,text="Total Income",font='times 15',bd=5,command=total).place(x=601,y=600)
    Label(root,text='Last Date Of Tax Filing is 31 March,Hurry Up!!!',bg="powder blue",fg="red",font='times 20').place(x=430,y=690)
    Button(root,text="click here to open new/exsisting filing",font='times 15',bd=5,command=new).place(x=1001,y=730)
    root.mainloop()

toe = Tk()
toe.configure(bg='powder blue')
toe.title("Python Project")    
toe.minsize(500,1000)
Label(toe,text=("My Python Project On Income Tax E-Filing System"),fg="blue",font='Adobe 45',bg="khaki").grid(row=0,column=0,sticky=W)
aaa=PhotoImage(file="tax4.gif")
Label(toe,image=aaa,height=400).grid(row=1,column=0)
Label(toe,text=("Name=HARSH RAJ"),fg="goldenrod",font='Broadway 25',bg="powder blue").grid(row=3,column=0,sticky=W)
Label(toe,text=("Enrollment No.-161B088"),fg="goldenrod",font='Broadway 25',bg="powder blue").grid(row=4,column=0,sticky=W)
Label(toe,text=("Branch- C.S.E"),fg="goldenrod",font='Broadway 25',bg="powder blue").grid(row=5,column=0,sticky=W)
Label(toe,text=("Batch- BX (B3)"),fg="goldenrod",font='Broadway 25',bg="powder blue").grid(row=6,column=0,sticky=W)
Label(toe,text=("Mobile No.- 7759090300"),fg="goldenrod",font='Broadway 25',bg="powder blue").grid(row=7,column=0,sticky=W)
Label(toe,text=("Wait This G.U.I Will Terminate Automatically After 10 Seconds."),fg="goldenrod",font='Broadway 25',bg="powder blue").grid(row=2,column=0,sticky=W)
Label(toe,text=("EMail Address- ryder.harsh@gmail.com"),fg="goldenrod",font='Broadway 25',bg="powder blue").grid(row=8,column=0,sticky=W)
toe.after(5000,fun)
toe.mainloop()

